name: Build Theos Tweak

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Theos and iOS SDK
      uses: upm-packages/setup-theos@v1

    - name: Compile Tweak
      run: |
        make package FINALPACKAGE=1

    - name: Upload Build Artifacts
      uses: actions/upload-artifact@v4
      with:
        name: TimeMarkGPSTweak
        path: |
          .theos/obj/*.dylib
          packages/*.deb
